# Generated by Django 5.1.3 on 2025-01-20 17:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducenterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('logo', models.ImageField(default='logo/default.jpg', upload_to='logo/', verbose_name='Logotip')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('parent', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'EducenterModel',
                'verbose_name_plural': 'EducenterModels',
                'db_table': 'EduCenter',
            },
        ),
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('days', models.CharField(choices=[('Toq kunlar', 'Toq kunlar'), ('Juft kunlar', 'Juft kunlar')], max_length=255)),
                ('starting_time', models.TimeField()),
                ('starting_day', models.DateField()),
                ('price', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'GroupModel',
                'verbose_name_plural': 'GroupModels',
                'db_table': 'Group',
            },
        ),
        migrations.CreateModel(
            name='JournalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'JournalModel',
                'verbose_name_plural': 'JournalModels',
                'db_table': 'Journal',
            },
        ),
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'RegisterModel',
                'verbose_name_plural': 'RegisterModel',
                'db_table': 'Register',
            },
        ),
        migrations.CreateModel(
            name='RoomsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'RoomsModel',
                'verbose_name_plural': 'RoomsModels',
                'db_table': 'Rooms',
            },
        ),
    ]
