# Generated by Django 5.1.3 on 2025-01-20 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('educenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('Ayol', 'Ayol'), ('Erkak', 'Erkak')], default='Erkak', max_length=50)),
                ('birth_day', models.DateField(blank=True, null=True)),
                ('role', models.IntegerField(choices=[(1, 'SUPER_ADMIN'), (2, 'ADMIN'), (3, 'CEO'), (4, 'ADMINISTRATOR'), (5, 'MANGER'), (6, 'CASHER'), (7, 'TEACHER')], default=7)),
                ('status', models.CharField(choices=[('Aktiv', 'Aktiv'), ('Aktiv emas', 'Aktiv emas')], default='Aktiv', max_length=255)),
                ('photo', models.ImageField(blank=True, default='avatar/default.jpg', null=True, upload_to='avatar/')),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('educenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educenter.educentermodel')),
            ],
            options={
                'verbose_name': 'UserModel',
                'verbose_name_plural': 'UserModels',
                'db_table': 'User',
            },
        ),
    ]
