# Generated by Django 5.1.3 on 2025-01-20 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('educenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template', models.FileField(upload_to='certificate_templates/')),
            ],
            options={
                'verbose_name': 'CertificatetypeModel',
                'verbose_name_plural': 'CertificatetypeModels',
                'db_table': 'CertificateType',
            },
        ),
        migrations.CreateModel(
            name='CourceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('duration', models.IntegerField(choices=[(30, 30), (40, 40), (60, 60), (90, 90), (120, 120), (180, 180), (240, 240), (280, 280), (300, 300)], default=90, verbose_name='Darslar muddati')),
                ('month_duration', models.IntegerField(verbose_name='Oylik Muddati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('educenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educenter.educentermodel')),
            ],
            options={
                'verbose_name': 'CourceModel',
                'verbose_name_plural': 'CourceModels',
                'db_table': 'Cource',
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Ayol', 'Ayol'), ('Erkak', 'Erkak')], default='Erkak', max_length=50)),
                ('birth_day', models.DateField()),
                ('status', models.CharField(choices=[('Aktiv', 'Aktiv'), ('Aktiv emas', 'Aktiv emas')], default='Aktiv', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('educenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educenter.educentermodel')),
            ],
            options={
                'verbose_name': 'StudentModel',
                'verbose_name_plural': 'StudentModels',
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='CertificateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='educenter.groupmodel')),
                ('certificate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='students.certificatetypemodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='students.studentmodel')),
            ],
            options={
                'verbose_name': 'CertificateModel',
                'verbose_name_plural': 'CertificateModels',
                'db_table': 'Certificate',
            },
        ),
    ]
